## cartridge.properties for cartridge app_custom_export_orders
#Wed Sep 23 21:42:47 CEST 2024
demandware.cartridges.app_custom_export_orders.multipleLanguageStorefront=true
demandware.cartridges.app_custom_export_orders.id=app_custom_export_orders